export let Departments = [
  "Agriculture Production and Farmers' Welfare Department",
  "Animal/Sheep Husbandry Deptt.",
  "ARI and Trainings Department",
  "Civil Aviation Department",
  "Cooperative Department",
  "Department of Culture",
  "Department of Food, Civil Supplies and Consumer Affairs",
  "Department of Horticulture",
  "Department of Law, Justice & Parliamentary Affairs",
  "Department of Mining",
  "Department of Skill Development",
  "Disaster Management Relief, Rehabilitation and Reconstruction Department",
  "Education Department",
  "Election Department",
  "Estates Department",
  "Finance Department",
  "Forest Department",
  "General Administration Department",
  "Health and Medical Education Department",
  "Higher Education Department",
  "Home Department",
  "Hospitality and Protocol Department",
  "Housing and Urban Development Department",
  "Industries & Commerce Department",
  "Information Department",
  "Information Technology Department",
  "Jal Shakti Department",
  "Labour and Employment Department",
  "Ladakh Affairs Department",
  "Lieutenant Governor's Office",
  "Planning, Development and Monitoring Department",
  "Power Development Department",
  "Public Works Department",
  "Revenue Department",
  "Rural Development Department and Panchayati Raj",
  "Science and Technology Department",
  "Social Welfare Department",
  "Tourism Department",
  "Transport Department",
  "Tribal Affairs Department",
];
